### ISSUE TITLE
Bridge not communicating 

### ISSUE THREAD

**Issue by saori-yuko** [TheHellBox/KISS-multiplayer#131]
Env: 
- Fedora 37 flatpak/not flatpak
- Wine and Native BeamNG 0.27.1

### How to reproduce environment used *requires* flatpak-builder
_com.github.TheHellBox.KISS-multiplayer.yml_
```
id: com.github.TheHellBox.KISS-multiplayer
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
command: kissmp-bridge

sdk-extensions:
  - org.freedesktop.Sdk.Extension.rust-stable

finish-args:
  - --share=ipc
  - --share=network

modules:
  - name: kissmp-bridge
    sources:
      - type: git
        url: https://github.com/TheHellBox/KISS-multiplayer.git
        tag: 0.5.0
        commit: 07ac644d3b89ecce61718180c36d4db896d0be39
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      append-path: /usr/lib/sdk/rust-stable/bin
      env:
        CARGO_HOME: /run/build/KISS-multiplayer/cargo
    build-commands: 
       - cargo build -p kissmp-bridge --release
       - install -Dm755 -t /app/bin/ target/release/kissmp-bridge
```
`flatpak install org.freedesktop.Sdk/x86_64/22.08 org.freedesktop.Sdk.Extension.rust-stable/x86_64/22.08`
`flatpak-builder build com.github.TheHellBox.KISS-multiplayer.yml --install --user --force-clean`
`flatpak run com.github.TheHellBox.KISS-multiplayer`

### Results
* Bad packets on loopback
* Cannot connect to servers
* 1/20 times connection is successful
